### ISSUE TITLE
stuck

### ISSUE THREAD

**Issue by Gamerappa** [kessanro/CR-game#1]
i have a problem playing this game there is some invisible barrier at the beginning

**Comment by bluethefoxyt** [comment]
send a screenshot

**Comment by Gamerappa** [comment]
how

**Comment by bluethefoxyt** [comment]
drag a screenshot into the comment box

**Comment by Gamerappa** [comment]
![barrier](https://cloud.githubusercontent.com/assets/21281176/19654371/f1455520-99e5-11e6-9492-0dd600b9efa0.PNG)
yes this is real

**Comment by Gamerappa** [comment]
so please fix it

**Comment by bluethefoxyt** [comment]
that is not a barrier you dont go there is just becuase of the charicter

**Comment by Gamerappa** [comment]
but can i do that?

**Comment by bluethefoxyt** [comment]
that is jsut to show how the engine works

**Comment by Gamerappa** [comment]
k
